//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demotivator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Demotivator()
        {
            this.DemotivatorRates = new HashSet<DemotivatorRate>();
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public string DemotivatorName { get; set; }
        public string Rate { get; set; }
        public System.DateTime Date { get; set; }
        public string CreatorName { get; set; }
        public string DemotivatorUrl { get; set; }
        public string OriginalImageUrl { get; set; }
        public string TopLine { get; set; }
        public string BottomLine { get; set; }
        public string AspNetUserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemotivatorRate> DemotivatorRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
