//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        public int Id { get; set; }
        public bool IsLiked { get; set; }
        public int CommentId { get; set; }
        public string AspNetUserId { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
