//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tag_to_dem
    {
        public int Id { get; set; }
        public int DemotivatorId { get; set; }
        public int tagId { get; set; }
    
        public virtual Demotivator Demotivator { get; set; }
        public virtual tag tag { get; set; }
    }
}
