//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public System.DateTime PublicationDate { get; set; }
        public string CommentText { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Demotivator Demotivator { get; set; }
    }
}
